# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    import matplotlib.pyplot as plt
    import numpy as np
    import matplotlib.ticker as ticker
    from shiny.express import render, ui


    def sin(a, b):
      fig, ax = plt.subplots()
      x = np.linspace(0, 10, 10000) #retorna 100 valores entre 0 e 10
      y = np.sin(int(a)*x+int (b))
      plt.plot(x, y, linewidth = 1)
      ax.set(xlim=(0, 8), xticks=np.arange(1, 8),
             ylim=(-1.5, 1.5), yticks=np.arange(-1, 2))

    ui.input_slider("sliderA", "Slider", 0, 25, 1, animate = True)
    ui.input_slider("sliderB", "Slider", 0, 25, 1 , animate = True)

    # ========================================================================

    @render.plot
    def value():
      return sin(input.sliderA(), input.sliderB())

    # ========================================================================



    return None


_static_assets = ["TesteSeno_files","TesteSeno_files\\libs\\quarto-html\\tippy.css","TesteSeno_files\\libs\\quarto-html\\quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css","TesteSeno_files\\libs\\quarto-html\\quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css","TesteSeno_files\\libs\\bootstrap\\bootstrap-icons.css","TesteSeno_files\\libs\\bootstrap\\bootstrap-890b18279d630a8af0357820e6fbb7bc.min.css","TesteSeno_files\\libs\\bootstrap\\bootstrap-dark-890b18279d630a8af0357820e6fbb7bc.min.css","TesteSeno_files\\libs\\clipboard\\clipboard.min.js","TesteSeno_files\\libs\\quarto-html\\quarto.js","TesteSeno_files\\libs\\quarto-html\\tabsets\\tabsets.js","TesteSeno_files\\libs\\quarto-html\\axe\\axe-check.js","TesteSeno_files\\libs\\quarto-html\\popper.min.js","TesteSeno_files\\libs\\quarto-html\\tippy.umd.min.js","TesteSeno_files\\libs\\quarto-html\\anchor.min.js","TesteSeno_files\\libs\\bootstrap\\bootstrap.min.js","TesteSeno_files\\libs\\quarto-dashboard\\quarto-dashboard.js","TesteSeno_files\\libs\\quarto-dashboard\\stickythead.js","TesteSeno_files\\libs\\quarto-dashboard\\web-components.js","TesteSeno_files\\libs\\quarto-dashboard\\components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "TesteSeno.html",
    server,
    static_assets=_static_assets,
)
